/**
 * Author: Greg Mazo
 * Date Modified: Mar 6, 2021
 * Copyright (C) 2021 Gregory Mazo
 * 
 */
/**
 
 * 
 */
package testing;

/**
 
 * 
 */
public enum TestExample{ 
	DIVERSE_SHAPES, RECTANGLE_AND_OTHERS, MANY_COLORS, MANY_STROKES , MANY_ANGLES,MANY_ANGLE_TEXT , MANY_ANGLE_COMPLEX_TEXT , MULTIPLE_FONTS,MULTIPLE_FONT_DIMS, MANY_ARROWS, EMPTY,
	SPLIT_CHANNEL_FIGURE, MERGE_PANEL_FIGURE, FIGURE_WITH_INSETS, MANY_SPLIT_CHANNEL, MANY_SPLIT_CHANNEL_SCRAMBLE, MANY_SPLIT_CHANNEL_SCRAMBLE_LIGHT,
	COLUMN_PLOTS, XY_PLOTS, GROUPED_PLOTS, KM_PLOTS;
	}

