/*******************************************************************************
 * Copyright (c) 2021 Gregory Mazo
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *******************************************************************************/

package genericMontageLayoutToolKit;

import icons.IconSet;
import layout.basicFigure.LayoutSpaces;
import logging.IssueLog;

/**
written to determine whether icon objects generated by code are really generated faster than those
loaded from jpeg files. these icons from this test are no longer used.
jpeg files are used for relatively few icons
 */
public class RowSwapperToolIconTest {

	//@Test//test does not need to be regularly performed
	public void test() {
		long time=System.currentTimeMillis();
		new RowSwapperToolIcon(0, LayoutSpaces.COLS).generateIconSet();
		
		IssueLog.sytemprint=true;
		IssueLog.log("time taken for new tool creates "+(System.currentTimeMillis()-time));
		
		time=System.currentTimeMillis();
		new IconSet("icons/ColumnSwapperIcon.jpg","icons/ColumnSwapperPressIcon.jpg","icons/ColumnSwapperRollIcon.jpg");
		IssueLog.log("time taken for old tool creates "+(System.currentTimeMillis()-time));
		
		
		time=System.currentTimeMillis();
		new RowSwapperToolIcon(0, LayoutSpaces.ROWS).generateIconSet();
		
		IssueLog.sytemprint=true;
		IssueLog.log("time taken for new tool creates second time "+(System.currentTimeMillis()-time));
		
		time=System.currentTimeMillis();
		new IconSet("icons/ColumnSwapperIcon.jpg","icons/ColumnSwapperPressIcon.jpg","icons/ColumnSwapperRollIcon.jpg");
		IssueLog.log("time taken for old tool creates second time "+(System.currentTimeMillis()-time));
		
	}

}
